package types

const (
	NOTIFY_DYNAMICE = iota
	NOTIFY_UNREAD
	NOTIFY_READ
)
const (
	NOTIFY_TYPE_UNIMPORTANT = iota + 1
	NOTIFY_TYPE_NEED_CONFIRM
	NOTIFY_TYPE_ERROR
	NOTIFY_TYPE_INSTALL_LOG
	NOTIFY_TYPE_PERSION_FIRNED_LEAVE
	NOTIFY_TYPE_PERSION_FIRNED_LIVE
)

const (
	NOTIFY_APP = iota
)
