name: "App Request"
description: "Request to add an app to the app store."
title: "[App Request] AppName"
labels: ["App Request"]
body:
  - type: markdown
    attributes:
      value: |
        ### â¤ Thanks for taking the time to fill out this app request!
        > Before proceeding, please make sure that this app is not in App Store and no one has [requested](https://github.com/IceWhaleTech/CasaOS/labels/App%20Request) the same app before.
        > If you have already requested the app, please ask your friends to help add a ðŸ‘ to this issue. Then be patient and wait for the developers to work on it.
        > If you have any questions, please ask them on [Discord](https://discord.gg/knqAbbBbeX) or [Github Discussions](https://github.com/IceWhaleTech/CasaOS/discussions).

  - type: textarea
    id: app-info
    attributes:
      label: "App Information"
      description: "The formal information of this app, as detailed as possible."
      value: |
        - Name: <!-- eg. Nextcloud -->
        - Short Description: <!-- eg. Personal cloud and file sharing solution -->
        - Official Website: <!-- If available. eg. https://nextcloud.com -->
        - GitHub Repository: <!-- If available. eg. https://github.com/nextcloud/server -->
        - Docker Image: <!-- If available. eg. nextcloud/server:latest, ghcr.io/nextcloud/server:latest -->
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: "Why do you want this app?"
      description: "Detailed notes can help developers and others understand the importance of this app."
      placeholder: |
        As a [what role], it helps me solve [what problem], and especially [what function] is great!
        or
        It solves [what problem] and especially [what feature] works well, which is hard to do with other app.
        or
        This is the app that [some device/service] must use and will not work without it.
        or 
        others

  - type: textarea
    id: additional-info
    attributes:
      label: "Additional information?"
      description: "Anything else you want to share with the developers and others?"
      placeholder: |
        Example:
        - Noteworthy matters.
        - Recommended Docker image.
        - Validated Docker deployment instructions.
        - Notable Docker setup details.
        - Recommended config files, user data, accessible directory settings.