blank_issues_enabled: false
contact_links:
  - name: Questions, Ideas, Discussions
    url: https://github.com/IceWhaleTech/CasaOS/discussions
    about: Ask questions, propose ideas, or discuss anything related to CasaOS
