name: "1. Feedback"
description: Feedback, showcases, thoughts, needs and questions, etc.
title: "[Feedback] "
labels: ["feedback"]
assignees:
  - JohnGuan
  - ETWang1991
body:
  - type: markdown
    attributes:
      value: |
        ### ❤️ Thanks for your feedback!
        > Come join our [Discord community](https://discord.gg/knqAbbBbeX) and paint the ideal home cloud with us.
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What do you want to tell us?
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Please add logs/files/screenshots if you have them to help us better understanding.

