name: Push Events to Discord

on:
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created
  discussion:
    types:
      - created
      - transferred
      - answered
  discussion_comment:
    types:
      - created

jobs:
  push-events:
  
    runs-on: ubuntu-latest
    
    steps:
      
      - name: General Discussions & Comments
        if: ${{ ( github.event_name == 'discussion' || github.event_name == 'discussion_comment' ) && github.event.discussion.category.name == 'General' }}
        uses: joseph-montanez/forward-event-action@v3.0.0
        with:
          webhook: ${{ secrets.Discord_CasaOS_General_Webhook }}
    
      - name: App Request Issues & Comments
        if: ${{ ( github.event_name == 'issues' || github.event_name == 'issue_comment' ) && contains(github.event.issue.labels.*.name, 'App Request') }}
        uses: joseph-montanez/forward-event-action@v3.0.0
        with:
          webhook: ${{ secrets.Discord_CasaOS_App_Request_Webhook }}
          
      - name: Bug Issues & Comments
        if: ${{ ( github.event_name == 'issues' || github.event_name == 'issue_comment' ) && contains(github.event.issue.labels.*.name, 'bug') && !contains(github.event.issue.labels.*.name, 'alpha') }}
        uses: joseph-montanez/forward-event-action@v3.0.0
        with:
          webhook: ${{ secrets.Discord_CasaOS_Bug_Webhook }}
